services:
  front:
    build: ./front
    container_name: zombieland-front
    ports:      
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/

  back:
    build: ./back
    container_name: zombieland-back
    ports:
      - "5000:5000"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
